Construct a matrix below ; 

$$\left[\begin{array}{ccc} 1 & 0.2 & 0.5 \\ 0.2 & 1 & 0.8 \\ 0.5 & 0.8 & 1 \end{array}\right]$$

as a NumPy array.

In [1]:
import numpy as np

In [2]:
matrix = np.array([[1, 0.2, 0.5],
                   [0.2, 1, 0.8],
                   [0.5, 0.8, 1]])

In [3]:
#Compute the inversion of the matrix (transpose)
transpose_matrix = np.linalg.inv(matrix)
print(transpose_matrix)

[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [4]:
#Compute the determinant of the matrix
determinant = np.linalg.det(matrix)
print(determinant)

0.2299999999999999
